-- 1. Licni_podaci_korisnika
CREATE TABLE Licni_podaci_korisnika (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Ime VARCHAR2(50) NOT NULL,
    Prezime VARCHAR2(50) NOT NULL
);

-- 2. Adresa_korisnika
CREATE TABLE Adresa_korisnika (
    ID NUMBER PRIMARY KEY,
    Ulica VARCHAR2(100),
    Grad VARCHAR2(50),
    Drzava VARCHAR2(50),
    FOREIGN KEY (ID) REFERENCES Licni_podaci_korisnika(ID)
);

-- 3. Contact_korisnika
CREATE TABLE Contact_korisnika (
    ID NUMBER PRIMARY KEY,
    Broj_telefona VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE NOT NULL,
    FOREIGN KEY (ID) REFERENCES Licni_podaci_korisnika(ID)
);

-- 4. Nalog_korisnika
CREATE TABLE Nalog_korisnika (
    ID NUMBER PRIMARY KEY,
    Korisnicko_ime VARCHAR2(50) UNIQUE NOT NULL,
    Lozinka VARCHAR2(100) NOT NULL,
    Tip_korisnika VARCHAR2(20) NOT NULL,
    Blokiran NUMBER(1) DEFAULT 0,
    FOREIGN KEY (ID) REFERENCES Licni_podaci_korisnika(ID)
);

-- 5. Osnovni_podaci_objave
CREATE TABLE Osnovni_podaci_objave (
    ID NUMBER PRIMARY KEY,
    ID_Korisnika NUMBER NOT NULL,
    Broj_odbijanja NUMBER DEFAULT 0,
    Status VARCHAR2(20) NOT NULL,
    FOREIGN KEY (ID_Korisnika) REFERENCES Nalog_korisnika(ID)
);

-- 6. Sadrzaj_objave
CREATE TABLE Sadrzaj_objave (
    ID NUMBER PRIMARY KEY,
    Osnovni_podaci_ID NUMBER,  -- Nova kolona za povezivanje sa Osnovni_podaci_objave
    Tekst CLOB,
    Slika VARCHAR2(255),
    FOREIGN KEY (Osnovni_podaci_ID) REFERENCES Osnovni_podaci_objave(ID)  -- Spoljni kljuè
);



-- 7. Prijateljstva
CREATE TABLE Prijateljstva (
    ID NUMBER PRIMARY KEY,
    ID_Korisnika1 NUMBER NOT NULL,
    ID_Korisnika2 NUMBER NOT NULL,
    Status VARCHAR2(20) NOT NULL,
    UNIQUE (ID_Korisnika1, ID_Korisnika2),
    FOREIGN KEY (ID_Korisnika1) REFERENCES Nalog_korisnika(ID),
    FOREIGN KEY (ID_Korisnika2) REFERENCES Nalog_korisnika(ID)
);

-- 8. Osnovni_podaci_notifikacije
CREATE TABLE Osnovni_podaci_notifikacije (
    ID NUMBER PRIMARY KEY,
    ID_Korisnika NUMBER NOT NULL,
    Status VARCHAR2(20) NOT NULL,
    FOREIGN KEY (ID_Korisnika) REFERENCES Nalog_korisnika(ID)
);

-- 9. Sadrzaj_notifikacije
CREATE TABLE Sadrzaj_notifikacije (
    ID NUMBER PRIMARY KEY,
    Osnovni_podaci_ID NUMBER,  -- Nova kolona za povezivanje sa Osnovni_podaci_notifikacije
    Tekst CLOB NOT NULL,
    Datum_vreme_slanja TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Osnovni_podaci_ID) REFERENCES Osnovni_podaci_notifikacije(ID)  -- Spoljni kljuè
);


-- Kreiranje sekvenci za generisanje ID vrednosti
CREATE SEQUENCE Licni_podaci_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Adresa_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Contact_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Nalog_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Objave_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Sadrzaj_objave_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Prijateljstva_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Notifikacije_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Sadrzaj_notifikacije_seq START WITH 1 INCREMENT BY 1;




--DROP SEQUENCE Licni_podaci_seq;
--DROP SEQUENCE Adresa_seq;
--DROP SEQUENCE Contact_seq;
--DROP SEQUENCE Nalog_seq;
--DROP SEQUENCE Objave_seq;
--DROP SEQUENCE Prijateljstva_seq;
--DROP SEQUENCE Notifikacije_seq;
--DROP SEQUENCE Sadrzaj_objave_seq;

--drop table Licni_podaci_korisnika;
--drop table Adresa_korisnika;
--drop table Contact_korisnika;
--drop table Nalog_korisnika;
--drop table Osnovni_podaci_objave;
--drop table Sadrzaj_objave;
--drop table Prijateljstva;
--drop table Osnovni_podaci_notifikacije;
--drop table Sadrzaj_notifikacije;



